//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _598A4TV.A4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="A4.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVerification", ReplyAction="http://tempuri.org/IService1/GetVerificationResponse")]
        string GetVerification(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVerification", ReplyAction="http://tempuri.org/IService1/GetVerificationResponse")]
        System.Threading.Tasks.Task<string> GetVerificationAsync(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xPathSearch", ReplyAction="http://tempuri.org/IService1/xPathSearchResponse")]
        string xPathSearch(string xmlUrl, string xPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xPathSearch", ReplyAction="http://tempuri.org/IService1/xPathSearchResponse")]
        System.Threading.Tasks.Task<string> xPathSearchAsync(string xmlUrl, string xPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : _598A4TV.A4.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<_598A4TV.A4.IService1>, _598A4TV.A4.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVerification(string xmlUrl, string xsdUrl) {
            return base.Channel.GetVerification(xmlUrl, xsdUrl);
        }
        
        public System.Threading.Tasks.Task<string> GetVerificationAsync(string xmlUrl, string xsdUrl) {
            return base.Channel.GetVerificationAsync(xmlUrl, xsdUrl);
        }
        
        public string xPathSearch(string xmlUrl, string xPath) {
            return base.Channel.xPathSearch(xmlUrl, xPath);
        }
        
        public System.Threading.Tasks.Task<string> xPathSearchAsync(string xmlUrl, string xPath) {
            return base.Channel.xPathSearchAsync(xmlUrl, xPath);
        }
    }
}
